### ISSUE TITLE
define what exactly a neighbourhood/kiez is

### ISSUE THREAD

**Issue by KonstiSchaetz** [smallbusinesshero/business#1]
- How do we make sure, that on the webapp customers look exactly for the kiez they're living in? they might not know the name and look rather for "Friedrichshain" instead of "Samariterkiez" (new in town, non-german speakers)  --> by location?

- Where do we draw the line? many "kieze" are rather colloquial/local knowledge, no? --> draw a 2km radius around location?

- do we not need a list with all names of neighbourhoods in a City which we can provide via droplist on the app?

**Comment by cnasenberg** [comment]
Neighborhoods are like labels. A store can have multiple of them. It can at the same time cover several 'Kieze' z.B. Boxhagener Platz and Boxhagener Kiez - and at the same time have the district e.g. Friedrichshain as an additional neighborhood. We also added a geolocation search, which will make it even easier. 

All in all: Stores can pick several Kieze/Viertel around them, especially if they are somewhere near the border of one.
