### ISSUE TITLE
We need to support different store owner contact types.

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/business#2]
- different phone numbers with label (z.B. whatsapp or phone)
- different URLs with label (e.g. instagram, facebook) 
- one email address (stays as it is). 

Acceptance Criteria
- Data structure for frontend and backend (API) is defined. 
- Fields are available in backend. 
- UX/UI is adapted. 
- Frontend is adapted accordingly.

**Comment by KonstiSchaetz** [comment]
Im not sure, if I understand correctly. 

do you mean we need seperate columns in our spreadsheet? or has it become obsolete with our new google formular?
